[package]
name = "partior"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
metaheuristics-nature = { version = "8.0.4", features = ["rayon"] }
#metaheuristics-nature = { version = "8.0.4" }
num = "0.4.0"
num-integer = "0.1.45"
once_cell = "1.17.1"
petgraph = "0.6.2"
rand = "0.8.5"
rs-graph = "0.20.1"
scan_fmt = "0.2.6"
statrs = "0.16.0"

[lib]
name = "partior"
path = "src/lib.rs"
crate-type = ["dylib"]
